version: '2'
services:
  webapp:
    build: .
    image: carnival-web
    links:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      # Mounting .carnival dir
      - .:/usr/src/carnival
      # Logs volume
      - /tmp/log/carnival:/var/log/carnival

    environment:
      - DJANGO_SETTINGS_MODULE=carnival_web.settings.production
      - CARNIVAL_POSTGRES_HOST=postgres
      - CARNIVAL_POSTGRES_USERNAME=carnival
      - CARNIVAL_POSTGRES_PASSWORD=carnival

  postgres:
    image: postgres:9.5
    environment:
      POSTGRES_USER: carnival
      POSTGRES_PASSWORD: carnival
      POSTGRES_DB: carnival_db
